# Generated by Django 4.1 on 2022-09-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatar",
            old_name="imagen",
            new_name="image",
        ),
    ]
